<?php
$text="A FTech, está no mercado a 1 ano, oferecendo serviço profissional personalizado, com originalidade, inovações e qualidade. Gerenciando soluções completas com manutenção de equipamentos. Nossos serviços garantem produtividade e segurança aos nossos clientes, além de promover o desempenho pessoal e profissional  de nossos colaboradores. Resultando em clientes satisfeitos. Nossa empresa possui excelente atendimento ao cliente possuindo uma das melhores avaliações do Grande Abc e toda a rede. A unidade tem como diferencial de atendimento e qualidade. Temos a maior rede de assistência técnica do Brasil e estamos sempre prontos para atender suas dúvidas ou necessidades. Aproveite e registre seu produto para que possamos conhecê-lo melhor. Entender o perfil de nossos consumidores irá nos ajudar a aprimorar nossos produtos e serviços.";
$logo=array(
    array(
        "",
        "Acer",
        "AMD",
        "Apple",
        "Asus",
        "Corsair",
        "Dell",
        "Galax",
        "Gigabyte",
        "HP",
        "HyperX",
        "Intel",
        "Kingston",
        "Lenovo",
        "Logitech",
        "Microsoft",
        "MSI",
        "NVidia",
        "Positivo",
        "Razer",
        "Redragon",
        "Samsung",
        "Seagate",
        "WD",
        "Zotac",
    ),
);
?>